### ISSUE TITLE
Feature Request: Binding to print out binding

### ISSUE THREAD

**Issue by gwlester** [suewonjp/tclsh-wrapper#2]
It would be nice if there was a binding, e.g. Control-?, that printed out all of the bindings.

**Comment by suewonjp** [comment]
OK. Let me add the feature for the next version.

**Comment by suewonjp** [comment]
Pull https://github.com/suewonjp/tclsh-wrapper/tree/v1.4rc and check it out, please.

I've decided to use `help` command rather than `Control-?` you suggested. The reasons are:

- Many shell applications provide `help` command so it's more common and intuitive
- Key bindings are valuable resources. I think it's a better strategy to allocate them for other functions rather than printing out messages

**Comment by suewonjp** [comment]
closing this
